apiVersion: v1
kind: pod
metadata:
  name: backend
Spec:
  initContainer:
  containers:
    - name: backend
      image: docker push 942136769355.dkr.ecr.us-east-1.amazonaws.com/expense-backend:latest
