apiVersion: v1
kind: pod
metadata:
  name: frontend
Spec:
  containers:
    - name: frontend
      image: docker push 942136769355.dkr.ecr.us-east-1.amazonaws.com/expense-frontend:latest
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer
  selector:
    appName: frontend
    projectName: expense
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
